// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuuE78FQ9FLOGb0wVhKnKTXejVCY4HUkY',
    appId: '1:992838576478:web:824eaf6afbe1a95000c7cf',
    messagingSenderId: '992838576478',
    projectId: 'qr-control-43d63',
    authDomain: 'qr-control-43d63.firebaseapp.com',
    storageBucket: 'qr-control-43d63.firebasestorage.app',
    measurementId: 'G-RQ95G2E8C9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjyAi-VPa0v0PujsDxfF1iJvDk9_9vbHM',
    appId: '1:992838576478:android:dc5e67db7512bb6000c7cf',
    messagingSenderId: '992838576478',
    projectId: 'qr-control-43d63',
    storageBucket: 'qr-control-43d63.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwrmdLIl85iKRR0U1hopvj010JnsRP2ts',
    appId: '1:992838576478:ios:38d4fdc4f2f3b7a300c7cf',
    messagingSenderId: '992838576478',
    projectId: 'qr-control-43d63',
    storageBucket: 'qr-control-43d63.firebasestorage.app',
    iosBundleId: 'com.example.qrControl',
  );
}
